import { ActivityLogEntry } from "@/models/activity-log";
import { subDays, subHours, subMinutes } from "date-fns";

export const DUMMY_ACTIVITY_LOGS: ActivityLogEntry[] = [
    {
      id: "1",
      userName: "Sarah Chen",
      userEmail: "sarah.chen@acme.com",
      userRole: "System Admin",
      userInitials: "SC",
      action: "Created User",
      actionVerb: "Created a new user account for",
      actionTarget: "john.doe@acme.com",
      description: "Created a new user account for john.doe@acme.com",
      category: "User Management",
      targetResource: "john.doe@acme.com",
      status: "success",
      ipAddress: "192.168.1.42",
      timestamp: subMinutes(new Date(), 15),
      iconType: "user",
    },
    {
      id: "2",
      userName: "Sarah Chen",
      userEmail: "sarah.chen@acme.com",
      userRole: "System Admin",
      userInitials: "SC",
      action: "Assigned Role",
      actionVerb: "Assigned",
      actionTarget: '"Data Manager" role to john.doe@acme.com',
      description: 'Assigned the "Data Manager" role to john.doe@acme.com',
      category: "User Management",
      targetResource: "john.doe@acme.com",
      status: "success",
      ipAddress: "192.168.1.42",
      timestamp: subHours(new Date(), 2),
      iconType: "user",
    },
    {
      id: "3",
      userName: "Michael Torres",
      userEmail: "m.torres@acme.com",
      userRole: "Organization Admin",
      userInitials: "MT",
      action: "Updated Building",
      actionVerb: "Updated energy data for",
      actionTarget: '"HQ Tower — Block A"',
      description: 'Updated energy data for "HQ Tower — Block A"',
      category: "Building Management",
      targetResource: "HQ Tower — Block A",
      status: "success",
      ipAddress: "10.0.0.88",
      timestamp: subHours(new Date(), 5),
      iconType: "building",
    },
    {
      id: "4",
      userName: "Emily Park",
      userEmail: "e.park@acme.com",
      userRole: "Data Manager",
      userInitials: "EP",
      action: "Exported Report",
      actionVerb: "Exported",
      actionTarget: "Q4 emissions report as CSV",
      description: "Exported Q4 emissions report as CSV",
      category: "Data Management",
      targetResource: "Q4 Emissions Report",
      status: "success",
      ipAddress: "172.16.0.15",
      timestamp: subHours(new Date(), 8),
      iconType: "data",
    },
    {
      id: "5",
      userName: "James Wilson",
      userEmail: "j.wilson@acme.com",
      userRole: "System Admin",
      userInitials: "JW",
      action: "Deleted User",
      actionVerb: "Attempted to delete user",
      actionTarget: "legacy_admin@acme.com",
      description: "Attempted to delete user legacy_admin@acme.com but the account is protected",
      category: "User Management",
      targetResource: "legacy_admin@acme.com",
      status: "failed",
      failureReason:
        "The target user account is a protected system account and cannot be deleted. Remove the protection flag first or contact the platform team.",
      ipAddress: "192.168.1.100",
      timestamp: subHours(new Date(), 12),
      iconType: "user",
    },
    {
      id: "6",
      userName: "Sarah Chen",
      userEmail: "sarah.chen@acme.com",
      userRole: "System Admin",
      userInitials: "SC",
      action: "Updated Organization",
      actionVerb: "Changed billing contact for",
      actionTarget: '"Acme Corp"',
      description: 'Changed billing contact for organization "Acme Corp"',
      category: "Organization Management",
      targetResource: "Acme Corp",
      status: "success",
      ipAddress: "192.168.1.42",
      timestamp: subDays(new Date(), 1),
      iconType: "org",
    },
    {
      id: "7",
      userName: "Emily Park",
      userEmail: "e.park@acme.com",
      userRole: "Data Manager",
      userInitials: "EP",
      action: "Updated Emission Factor",
      actionVerb: "Updated grid emission factor for",
      actionTarget: '"United States — 2025"',
      description: 'Updated grid emission factor for "United States — 2025"',
      category: "Emission Config",
      targetResource: "Grid Factor: US 2025",
      status: "success",
      ipAddress: "172.16.0.15",
      timestamp: subDays(new Date(), 1),
      iconType: "emission",
    },
    {
      id: "8",
      userName: "Michael Torres",
      userEmail: "m.torres@acme.com",
      userRole: "Organization Admin",
      userInitials: "MT",
      action: "Created Building",
      actionVerb: "Registered new building",
      actionTarget: '"Warehouse 7 — Dubai"',
      description: 'Registered new building "Warehouse 7 — Dubai"',
      category: "Building Management",
      targetResource: "Warehouse 7 — Dubai",
      status: "success",
      ipAddress: "10.0.0.88",
      timestamp: subDays(new Date(), 1),
      iconType: "building",
    },
    {
      id: "9",
      userName: "James Wilson",
      userEmail: "j.wilson@acme.com",
      userRole: "System Admin",
      userInitials: "JW",
      action: "Login Attempt",
      actionVerb: "Failed login attempt from",
      actionTarget: "unrecognized device",
      description: "Failed login attempt from unrecognized device",
      category: "Authentication",
      targetResource: "j.wilson@acme.com",
      status: "failed",
      failureReason:
        "The login attempt was blocked because it originated from an unrecognized device and IP address. Multi-factor authentication was not completed.",
      ipAddress: "203.0.113.55",
      timestamp: subDays(new Date(), 1),
      iconType: "auth",
    },
    {
      id: "10",
      userName: "Sarah Chen",
      userEmail: "sarah.chen@acme.com",
      userRole: "System Admin",
      userInitials: "SC",
      action: "Updated System Settings",
      actionVerb: "Changed session timeout from",
      actionTarget: "30 to 60 minutes",
      description: "Changed session timeout from 30 to 60 minutes",
      category: "System Settings",
      targetResource: "Session Configuration",
      status: "success",
      ipAddress: "192.168.1.42",
      timestamp: subDays(new Date(), 2),
      iconType: "settings",
    },
    {
      id: "11",
      userName: "Emily Park",
      userEmail: "e.park@acme.com",
      userRole: "Data Manager",
      userInitials: "EP",
      action: "Uploaded Data",
      actionVerb: "Uploaded fuel consumption data for",
      actionTarget: '"HQ Tower — Block B"',
      description: 'Uploaded fuel consumption data for "HQ Tower — Block B"',
      category: "Data Management",
      targetResource: "HQ Tower — Block B",
      status: "success",
      ipAddress: "172.16.0.15",
      timestamp: subDays(new Date(), 2),
      iconType: "data",
    },
    {
      id: "12",
      userName: "Michael Torres",
      userEmail: "m.torres@acme.com",
      userRole: "Organization Admin",
      userInitials: "MT",
      action: "Bulk Import",
      actionVerb: "Attempted bulk import of",
      actionTarget: "250 building records",
      description: "Attempted bulk import of 250 building records",
      category: "Building Management",
      targetResource: "Bulk Import Job #1042",
      status: "failed",
      failureReason:
        "The CSV file contained 12 rows with invalid country codes and 3 rows with duplicate building IDs. The import was rolled back. Please fix the errors and re-upload.",
      ipAddress: "10.0.0.88",
      timestamp: subDays(new Date(), 3),
      iconType: "building",
    },
    {
      id: "13",
      userName: "James Wilson",
      userEmail: "j.wilson@acme.com",
      userRole: "System Admin",
      userInitials: "JW",
      action: "Deactivated User",
      actionVerb: "Deactivated user account for",
      actionTarget: "temp_contractor@acme.com",
      description: "Deactivated user account for temp_contractor@acme.com",
      category: "User Management",
      targetResource: "temp_contractor@acme.com",
      status: "success",
      ipAddress: "192.168.1.100",
      timestamp: subDays(new Date(), 4),
      iconType: "user",
    },
    {
      id: "14",
      userName: "Sarah Chen",
      userEmail: "sarah.chen@acme.com",
      userRole: "System Admin",
      userInitials: "SC",
      action: "Created Organization",
      actionVerb: "Created new organization",
      actionTarget: '"GreenBuild LLC"',
      description: 'Created new organization "GreenBuild LLC"',
      category: "Organization Management",
      targetResource: "GreenBuild LLC",
      status: "success",
      ipAddress: "192.168.1.42",
      timestamp: subDays(new Date(), 5),
      iconType: "org",
    },
    {
      id: "15",
      userName: "Emily Park",
      userEmail: "e.park@acme.com",
      userRole: "Data Manager",
      userInitials: "EP",
      action: "Updated Cooling Config",
      actionVerb: "Modified cooling system parameters for",
      actionTarget: '"Data Center Alpha"',
      description: 'Modified cooling system parameters for "Data Center Alpha"',
      category: "Emission Config",
      targetResource: "Data Center Alpha — Cooling",
      status: "success",
      ipAddress: "172.16.0.15",
      timestamp: subDays(new Date(), 6),
      iconType: "emission",
    },
    {
      id: "16",
      userName: "Michael Torres",
      userEmail: "m.torres@acme.com",
      userRole: "Organization Admin",
      userInitials: "MT",
      action: "Deleted Building",
      actionVerb: "Deleted archived building",
      actionTarget: '"Old Office — Berlin"',
      description: 'Deleted archived building "Old Office — Berlin"',
      category: "Building Management",
      targetResource: "Old Office — Berlin",
      status: "success",
      ipAddress: "10.0.0.88",
      timestamp: subDays(new Date(), 7),
      iconType: "building",
    },
    {
      id: "17",
      userName: "James Wilson",
      userEmail: "j.wilson@acme.com",
      userRole: "System Admin",
      userInitials: "JW",
      action: "Updated Role",
      actionVerb: "Added",
      actionTarget: '"Export reports" permission to Data Manager role',
      description: 'Added "Export reports" permission to the Data Manager role',
      category: "User Management",
      targetResource: "Role: Data Manager",
      status: "success",
      ipAddress: "192.168.1.100",
      timestamp: subDays(new Date(), 8),
      iconType: "user",
    },
  ]