import { OperationalDataEntry } from "@/screens/add-building/schema";

export const DUMMY_ENERGY_CARRIERS: OperationalDataEntry[] = [
  {
    id: "1",
    type: "wood",
    category: "Solid fuel",
    subCategory: "Fire wood",
    childCategory: "Fire wood (log wood)",
    unit: "kwh",
    emmissionFactor: 0.01,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "2",
    type: "oil",
    category: "Solid fuel",
    subCategory: "Heavy fuel oil",
    childCategory: "Heavy fuel oil",
    unit: "kwh",
    emmissionFactor: 0.01,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "3",
    type: "wood",
    category: "Solid fuel",
    subCategory: "Fire wood",
    childCategory: "Fire wood (wood pellets)",
    unit: "kwh",
    emmissionFactor: 0.01,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "4",
    type: "oil",
    category: "Solid fuel",
    subCategory: "Light fuel oil",
    childCategory: "Light fuel oil",
    unit: "kwh",
    emmissionFactor: 0.01,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "5",
    type: "gas",
    category: "Solid fuel",
    subCategory: "Natural gas",
    childCategory: "Natural gas",
    unit: "kwh",
    emmissionFactor: 0.01,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "6",
    type: "fuel",
    category: "Solid fuel",
    subCategory: "Coal",
    childCategory: "Bituminous coal",
    unit: "kg",
    emmissionFactor: 2.5,
    epdType: "official",
    country: "TH",
  },
  {
    id: "7",
    type: "oil",
    category: "Liquid fuel",
    subCategory: "Diesel",
    childCategory: "Diesel B7",
    unit: "liters",
    emmissionFactor: 2.7,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "8",
    type: "gas",
    category: "Gaseous fuel",
    subCategory: "LPG",
    childCategory: "LPG (Propane)",
    unit: "kg",
    emmissionFactor: 2.9,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "9",
    type: "fuel",
    category: "Solid fuel",
    subCategory: "Bio-fuel",
    childCategory: "Sugarcane Bagasse",
    unit: "kg",
    emmissionFactor: 0.05,
    epdType: "generic",
    country: "TH",
  },
  {
    id: "10",
    type: "oil",
    category: "Liquid fuel",
    subCategory: "Kerosene",
    childCategory: "Domestic Kerosene",
    unit: "liters",
    emmissionFactor: 2.5,
    epdType: "generic",
    country: "TH",
  },
];