import { EPD } from "@/models/epd";

export const DUMMY_EPDS: EPD[] = [
  {
    id: "epd-1",
    name: "Structural concrete M6582A09 (C30/37, F4, 16, XC4, XF1, XA1, XD1, WA, slow)",
    country: "DE",
    category: "Minerals building products",
    subCategory: "Precast concrete elements and goods",
    childCategory: "Structural concrete",
    epdType: "official",
    kgCO2e: 169.40,
  },
  {
    id: "epd-2",
    name: "Shower Hoses",
    country: "DE",
    category: "Building service engineering",
    subCategory: "Sanitary",
    childCategory: "Mounting",
    epdType: "official",
    kgCO2e: 0.59,
  },
  {
    id: "epd-3",
    name: "ACC M35 Ready Mixed Concrete (RMC)",
    country: "IN",
    category: "Minerals building products",
    subCategory: "Ready mixed concrete",
    childCategory: "Ready mixed concrete",
    epdType: "generic",
    kgCO2e: 396.00,
  },
  {
    id: "epd-4",
    name: "semi-finished products - Kunststoffwerke Katzbach GmbH & Co. KG - EPP mold",
    country: "DE",
    category: "Plastics",
    subCategory: "Ready mixed concrete",
    childCategory: "Ready mixed concrete",
    epdType: "generic",
    kgCO2e: 396.00,
  },
  {
    id: "epd-5",
    name: "Synhtic Resin Plaster; Synthetic Resin",
    country: "KH",
    category: "Chemical products",
    subCategory: "Renders and plasters",
    childCategory: "Synthetic resin plaster",
    epdType: "generic",
    kgCO2e: 2137.64,
  },
  {
    id: "epd-6",
    name: "Ready-Mix Concrete C20/25",
    country: "KH",
    category: "Minerals building products",
    subCategory: "Ready mixed concrete",
    childCategory: "Ready mixed concrete",
    epdType: "generic",
    kgCO2e: 345.79,
  },
  {
    id: "epd-7",
    name: "Cement Mortar",
    country: "KH",
    category: "Minerals building products",
    subCategory: "Mortar (masonry)",
    childCategory: "Mortar",
    epdType: "generic",
    kgCO2e: 543.83,
  },
  {
    id: "epd-8",
    name: "Sand-Lime Brick",
    country: "KH",
    category: "Minerals building products",
    subCategory: "Sand lime brick",
    childCategory: "Sand lime brick",
    epdType: "generic",
    kgCO2e: 538.64,
  },
  {
    id: "epd-9",
    name: "Aerated Concrete P4 05 Non-Reinforced; Average Density 500 Kg/M3, Reinforcement",
    country: "KH",
    category: "Minerals building products",
    subCategory: "Aerated concrete",
    childCategory: "Aerated concrete",
    epdType: "generic",
    kgCO2e: 401.28,
  },
  {
    id: "epd-10",
    name: "Aluminium Profiles For Windows, Doors, And Facades - FEAL D.O.O. - Aluminium",
    country: "BA",
    category: "Metals",
    subCategory: "Aluminium",
    childCategory: "Aluminium profiles",
    epdType: "official",
    kgCO2e: 12.5,
  }
];
