import { OrganizationUser } from "@/models/user";

export const DUMMY_USERS: OrganizationUser[] = [
  {
    id: "1",
    name: "Sarah Connor",
    email: "sarah@system.com",
    role: "super_admin",
    organization: "-",
    countryAccess: "All Countries",
    lastLogin: "Feb 12, 2024 10:00 AM",
    status: "Active",
    permissions: {
      buildings: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      emissionConfig: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      users: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      reports: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      dashboard: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      dataManagement: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      organizations: {all: true, view: true, create: true, edit: true, delete: true, export: true},
      systemSettings: {all: true, view: true, create: true, edit: true, delete: true, export: true},
    },
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@acme.com",
    role: "org_admin",
    organization: "Acme Corp",
    countryAccess: "kh",
    lastLogin: "Feb 11, 2024 3:30 PM",
    status: "Active",
    permissions: {
      buildings: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      emissionConfig: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      users: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      reports: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      dashboard: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      dataManagement: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      organizations: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      systemSettings: {all: false, view: true, create: true, edit: true, delete: false, export: true},
    },
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@acme.com",
    role: "data_manager",
    organization: "Acme Corp",
    countryAccess: "vn",
    lastLogin: "Feb 10, 2024 9:15 AM",
    status: "Active",
    permissions: {
      buildings: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      emissionConfig: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      users: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      reports: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      dashboard: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      dataManagement: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      organizations: {all: false, view: true, create: true, edit: true, delete: false, export: true},
      systemSettings: {all: false, view: true, create: true, edit: true, delete: false, export: true},
    },
  },
  {
    id: "4",
    name: "Mike Johnson",
    email: "mike@global.com",
    role: "viewer",
    organization: "Global Industries",
    countryAccess: "All Countries",
    lastLogin: "Jan 20, 2024 11:00 AM",
    status: "Inactive",
    permissions: {
      buildings: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      emissionConfig: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      users: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      reports: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      dashboard: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      dataManagement: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      organizations: {all: false, view: true, create: false, edit: false, delete: false, export: true},
      systemSettings: {all: false, view: true, create: false, edit: false, delete: false, export: true},
    },
  },
];
