export const DUMMY_COUNTRY_SETTINGS = [
  {
    id: "1",
    name: "Cambodia",
    citiesCount: 12,
    status: "Active" as const,
    addedOn: "12 Jan 2024",
    cities: [
      { name: "Phnom Penh", isActive: true },
      { name: "Siem Reap", isActive: true },
      { name: "Battambang", isActive: true },
      { name: "Sihanoukville", isActive: true },
      { name: "Kampot", isActive: true },
      { name: "Kep", isActive: true },
      { name: "Kampong Cham", isActive: true },
      { name: "Kampong Thom", isActive: true },
      { name: "Pursat", isActive: true },
      { name: "Koh Kong", isActive: true },
      { name: "Kratic", isActive: true },
      { name: "Preah Vihear", isActive: true },
    ],
  },
  {
    id: "2",
    name: "India",
    citiesCount: 3,
    status: "Inactive" as const,
    addedOn: "12 Jan 2024",
    cities: [
      { name: "Mumbai", isActive: true },
      { name: "Delhi", isActive: true },
      { name: "Bangalore", isActive: true },
    ],
  },
  {
    id: "3",
    name: "Vietnam",
    citiesCount: 5,
    status: "Active" as const,
    addedOn: "15 Jan 2024",
    cities: [
      { name: "Hanoi", isActive: true },
      { name: "Da Nang", isActive: true },
      { name: "Ho Chi Minh City", isActive: true },
      { name: "Hai Phong", isActive: true },
      { name: "Can Tho", isActive: true },
    ],
  },
];
