import { DataManagementImportRow, DataManagementExportRow } from "@/models/data-management";

export const DUMMY_DATA_MANAGEMENT_IMPORTS: DataManagementImportRow[] = [
  {
    id: "1",
    fileName: "energy_q1_2026.csv",
    fileType: "CSV",
    fileSize: "2.4 MB",
    dataType: "Energy",
    buildings: 12,
    records: 4320,
    uploadedBy: "Sarah Chen",
    date: "2026-03-15",
    status: "Success",
  },
  {
    id: "2",
    fileName: "fuel_jan_2026.xlsx",
    fileType: "XLSX",
    fileSize: "1.1 MB",
    dataType: "Fuel",
    buildings: 8,
    records: 1560,
    uploadedBy: "James Park",
    date: "2026-03-12",
    status: "Partial",
  },
  {
    id: "3",
    fileName: "refrigerant_data.csv",
    fileType: "CSV",
    fileSize: "340 KB",
    dataType: "Refrigerant",
    buildings: 3,
    records: 180,
    uploadedBy: "Maria Lopez",
    date: "2026-03-10",
    status: "Failed",
  },
  {
    id: "4",
    fileName: "energy_feb_2026.csv",
    fileType: "CSV",
    fileSize: "3.8 MB",
    dataType: "Energy",
    buildings: 15,
    records: 6700,
    uploadedBy: "Sarah Chen",
    date: "2026-03-08",
    status: "Success",
  },
  {
    id: "5",
    fileName: "emission_factors_v3.xlsx",
    fileType: "XLSX",
    fileSize: "890 KB",
    dataType: "Emission Factors",
    buildings: 0,
    records: 245,
    uploadedBy: "Admin",
    date: "2026-03-05",
    status: "Processing",
  },
  {
    id: "6",
    fileName: "epd_materials_2026.csv",
    fileType: "CSV",
    fileSize: "1.6 MB",
    dataType: "EPD Data",
    buildings: 0,
    records: 890,
    uploadedBy: "James Park",
    date: "2026-03-01",
    status: "Success",
  },
];

export const DUMMY_DATA_MANAGEMENT_EXPORTS: DataManagementExportRow[] = [
  {
    id: "1",
    exportName: "scope2_report_q1.pdf",
    reportType: "Scope 2 Emissions Report",
    buildingsCount: 12,
    dateRange: "Jan–Mar 2026",
    format: "PDF",
    generatedBy: "Sarah Chen",
    date: "2026-03-16",
  },
  {
    id: "2",
    exportName: "energy_data_export.xlsx",
    reportType: "Energy Consumption Data",
    buildingsCount: 8,
    dateRange: "Jan–Feb 2026",
    format: "XLSX",
    generatedBy: "James Park",
    date: "2026-03-14",
  },
  {
    id: "3",
    exportName: "full_emissions_2025.csv",
    reportType: "Annual Emissions Summary",
    buildingsCount: 15,
    dateRange: "Jan–Dec 2025",
    format: "CSV",
    generatedBy: "Maria Lopez",
    date: "2026-03-10",
  },
  {
    id: "4",
    exportName: "fuel_analysis_q4.pdf",
    reportType: "Fuel Consumption Analysis",
    buildingsCount: 5,
    dateRange: "Oct–Dec 2025",
    format: "PDF",
    generatedBy: "Sarah Chen",
    date: "2026-03-05",
  },
];