import { Building } from "@/models/building";

export const DUMMY_BUILDINGS: Building[] = [
  {
    id: "1",
    name: "Becken Apartments",
    location: "Cambodia - Battambang",
    created_on: "6 Jan 2026",
    status: "Draft",
    total_emissions: "N/A",
    building_type: "Homes",
    assigned_to: {
      name: "Liam Miller",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liam",
    },
  },
  {
    id: "2",
    name: "HQ - Emerald Tower",
    location: "Vietnam - Hanoi",
    created_on: "5 Jan 2026",
    status: "Active",
    total_emissions: "1,240 tCO2e",
    building_type: "Apartments",
    assigned_to: {
      name: "Ava Thompson",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ava",
    },
  },
  {
    id: "3",
    name: "Distribution Center West",
    location: "Germany - Berlin",
    created_on: "4 Jan 2026",
    status: "Active",
    total_emissions: "1,100 tCO2e",
    building_type: "Hotels",
    assigned_to: {
      name: "Noah Garcia",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Noah",
    },
  },
  {
    id: "4",
    name: "Downtown Retail Branch",
    location: "India - Mumbai",
    created_on: "3 Jan 2026",
    status: "Active",
    total_emissions: "950 tCO2e",
    building_type: "Resort",
    assigned_to: {
      name: "Isabella Martinez",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella",
    },
  },
  {
    id: "5",
    name: "Fab 2 Manufacturing",
    location: "Nepal - Kathmandu",
    created_on: "2 Jan 2026",
    status: "Active",
    total_emissions: "800 tCO2e",
    building_type: "Retail",
    assigned_to: {
      name: "Ethan Robinson",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan",
    },
  },
  {
    id: "6",
    name: "Old Storage Facility",
    location: "Vietnam - Ho Chi Minh",
    created_on: "1 Jan 2026",
    status: "Active",
    total_emissions: "750 tCO2e",
    building_type: "Office",
    assigned_to: {
      name: "Mia Clark",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
    },
  },
  {
    id: "7",
    name: "Green Office Complex",
    location: "Germany - Munich",
    created_on: "31 Dec 2025",
    status: "Active",
    total_emissions: "600 tCO2e",
    building_type: "Healthcare",
    assigned_to: {
      name: "James Rodriguez",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    },
  },
  {
    id: "8",
    name: "St. James Plaza",
    location: "India - Delhi",
    created_on: "30 Dec 2025",
    status: "Draft",
    total_emissions: "N/A",
    building_type: "Education",
    assigned_to: {
      name: "Sofia Lewis",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    },
  },
  {
    id: "9",
    name: "Skyline Vista Tower",
    location: "Nepal - Pokhara",
    created_on: "29 Dec 2025",
    status: "Archived",
    total_emissions: "400 tCO2e",
    building_type: "Mixed Use",
    assigned_to: {
      name: "Benjamin Lee",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin",
    },
  },
  {
    id: "10",
    name: "Harmony Residences",
    location: "Cambodia - Phnom Penh",
    created_on: "28 Dec 2025",
    status: "Active",
    total_emissions: "350 tCO2e",
    building_type: "Homes",
    assigned_to: {
      name: "Chloe Walker",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe",
    },
  },
  {
    id: "11",
    name: "Harmony Residences",
    location: "Cambodia - Phnom Penh",
    created_on: "28 Dec 2025",
    status: "Active",
    total_emissions: "350 tCO2e",
    building_type: "Homes",
    assigned_to: {
      name: "Chloe Walker",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe",
    },
  },
  {
    id: "12",
    name: "Evergreen Corporate Center",
    location: "Vietnam - Da Nang",
    created_on: "27 Dec 2025",
    status: "Active",
    total_emissions: "300 tCO2e",
    building_type: "Apartments",
    assigned_to: {
      name: "Lucas Hall",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    },
  },
  {
    id: "13",
    name: "Pinnacle Business Park",
    location: "India - Kolkata",
    created_on: "25 Dec 2025",
    status: "Archived",
    total_emissions: "200 tCO2e",
    building_type: "Resort",
    assigned_to: {
      name: "Jackson Scott",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jackson",
    },
  },
  // Extra 7 buildings
  {
    id: "14",
    name: "Blue Sky Hotel",
    location: "Thailand - Bangkok",
    created_on: "20 Dec 2025",
    status: "Active",
    total_emissions: "1,500 tCO2e",
    building_type: "Hotels",
    assigned_to: {
      name: "Owen Young",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Owen",
    },
  },
  {
    id: "15",
    name: "Summit Heights",
    location: "Bhutan - Thimphu",
    created_on: "15 Dec 2025",
    status: "Active",
    total_emissions: "450 tCO2e",
    building_type: "Homes",
    assigned_to: {
      name: "Emma Wilson",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    },
  },
  {
    id: "16",
    name: "Ocean View Resort",
    location: "Maldives - Male",
    created_on: "10 Dec 2025",
    status: "Active",
    total_emissions: "2,000 tCO2e",
    building_type: "Resort",
    assigned_to: {
      name: "Aria Baker",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aria",
    },
  },
  {
    id: "17",
    name: "Urban Loft",
    location: "Japan - Tokyo",
    created_on: "5 Dec 2025",
    status: "Draft",
    total_emissions: "N/A",
    building_type: "Apartments",
    assigned_to: {
      name: "Leo Garcia",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo",
    },
  },
  {
    id: "18",
    name: "Central Tech Hub",
    location: "Singapore - Singapore",
    created_on: "1 Dec 2025",
    status: "Active",
    total_emissions: "850 tCO2e",
    building_type: "Office",
    assigned_to: {
      name: "Zoey Adams",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zoey",
    },
  },
  {
    id: "19",
    name: "Riverside Apartments",
    location: "Laos - Vientiane",
    created_on: "25 Nov 2025",
    status: "Active",
    total_emissions: "320 tCO2e",
    building_type: "Apartments",
    assigned_to: {
      name: "Nathaniel Reed",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nathaniel",
    },
  },
  {
    id: "20",
    name: "Sunset Plaza",
    location: "Myanmar - Yangon",
    created_on: "20 Nov 2025",
    status: "Archived",
    total_emissions: "150 tCO2e",
    building_type: "Retail",
    assigned_to: {
      name: "Abigail Hill",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Abigail",
    },
  },
];
