"use client";

import { DataManagementExportRow } from "@/models/data-management";
import { ColumnDef } from "@tanstack/react-table";
import { BaseTable } from "./base-table";
import { apiService } from "@/services/api.service";
import { Badge } from "@/components/ui/badge";
import { Download } from "lucide-react";

export const ExportsTable = () => {
  const columns: ColumnDef<DataManagementExportRow>[] = [
    {
      accessorKey: "exportName",
      header: "Export Name",
      cell: ({ row }) => (
        <div className="flex flex-col">
          <span className="font-medium text-foreground">
            {row.original.exportName}
          </span>
          <span className="text-secondary-foreground text-xs">
            {row.original.reportType}
          </span>
        </div>
      ),
    },
    {
      accessorKey: "dateRange",
      header: "Scope",
      cell: ({ row }) => (
        <div className="flex flex-col">
          <span className="font-medium text-foreground">
            {row.original.buildingsCount} buildings
          </span>
          <span className="text-secondary-foreground text-xs">
            {row.original.dateRange}
          </span>
        </div>
      ),
    },
    {
      accessorKey: "format",
      header: "Format",
      cell: ({ row }) => (
        <Badge variant="outline" className="font-medium px-2 py-0.5 text-[10px]">
          {row.original.format}
        </Badge>
      ),
    },
    {
      accessorKey: "generatedBy",
      header: "Generated By",
    },
    {
      accessorKey: "date",
      header: "Date",
    },
    {
      accessorKey: "actions",
      header: "Actions",
      cell: () => (
        <button className="flex items-center gap-1.5 text-xs font-medium text-foreground/80 hover:text-foreground">
          <Download className="size-3.5" />
          Download
        </button>
      ),
    },
  ];
  return (
    <BaseTable
      queryKey="data-management-exports"
      queryFn={(params) => apiService.getDataManagementExports(params)}
      columns={columns}
    />
  );
};
